-- Generated by scripts/extract_xlsx.py from 'JW_JJ_Hanna mods.xlsx'.
-- Boundary modifications: new geometry, new acreage, status -> Modify.
-- Safe to re-run.

update public.col_applications set
  status   = 'Modify',
  acreage  = 92.34,
  geometry = '{"type": "Polygon", "coordinates": [[[-94.70182, 29.47505], [-94.70699, 29.47286], [-94.70455, 29.47106], [-94.70275, 29.46837], [-94.70025, 29.47058], [-94.69782, 29.46775], [-94.69783, 29.47257], [-94.70182, 29.47505]]]}'::jsonb
where id = 7;

update public.col_applications set
  status   = 'Modify',
  acreage  = 93.76,
  geometry = '{"type": "Polygon", "coordinates": [[[-94.71944, 29.48726], [-94.73056, 29.4797], [-94.72813, 29.47804], [-94.71796, 29.48493], [-94.71944, 29.48726]]]}'::jsonb
where id = 16;

update public.col_applications set
  status   = 'Modify',
  acreage  = 91.22,
  geometry = '{"type": "Polygon", "coordinates": [[[-94.72691, 29.49113], [-94.73234, 29.48811], [-94.73117, 29.48603], [-94.73042, 29.48665], [-94.73034, 29.48427], [-94.72153, 29.49025], [-94.72209, 29.49106], [-94.72691, 29.49113]]]}'::jsonb
where id = 26;

update public.col_applications set
  status   = 'Modify',
  acreage  = 84.0,
  geometry = '{"type": "Polygon", "coordinates": [[[-94.72222, 29.48143], [-94.71611, 29.47565], [-94.71148, 29.4788], [-94.71722, 29.48143], [-94.72222, 29.48143]]]}'::jsonb
where id = 27;

update public.col_applications set
  status   = 'Modify',
  acreage  = 73.43,
  geometry = '{"type": "Polygon", "coordinates": [[[-94.70749, 29.47287], [-94.70416, 29.47511], [-94.71108, 29.47872], [-94.71533, 29.47585], [-94.7115, 29.47593], [-94.70901, 29.47288], [-94.70749, 29.47287]]]}'::jsonb
where id = 94;

update public.col_applications set
  status   = 'Modify',
  acreage  = 82.87,
  geometry = '{"type": "Polygon", "coordinates": [[[-94.71825, 29.48483], [-94.72787, 29.47787], [-94.72537, 29.47615], [-94.72377, 29.47617], [-94.72235, 29.47831], [-94.71735, 29.48169], [-94.71825, 29.48483]]]}'::jsonb
where id = 109;

