-- Generated by scripts/extract_xlsx.py -- do not edit by hand.
-- Re-runnable: existing rows keep their current status, everything else is refreshed.

insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (1, 'Justin', 'Accept', 'Pepper Grove Reef, Inc.', 'Galveston Bay', 82.25, '{"type": "Polygon", "coordinates": [[[-94.74382, 29.48087], [-94.74645, 29.48022], [-94.74827, 29.47494], [-94.74625, 29.47253], [-94.74499, 29.47293], [-94.74366, 29.47518], [-94.74208, 29.47555], [-94.74382, 29.48087]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (2, 'Justin', 'Decline', 'Pepper Grove Reef, Inc.', 'Galveston Bay', 10.84, '{"type": "Polygon", "coordinates": [[[-94.67396, 29.48727], [-94.67354, 29.48506], [-94.67197, 29.48325], [-94.67258, 29.48723], [-94.67396, 29.48727]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (3, 'Justin', 'Accept', 'Whitehead Reef, Inc.', 'Galveston Bay', 28.99, '{"type": "Polygon", "coordinates": [[[-94.86135, 29.51499], [-94.8623, 29.51288], [-94.85787, 29.51212], [-94.85582, 29.51381], [-94.86135, 29.51499]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (4, 'Justin', 'Decline', 'Whitehead Reef, Inc.', 'Galveston Bay', 33.82, '{"type": "Polygon", "coordinates": [[[-94.71193, 29.53236], [-94.71545, 29.53188], [-94.71552, 29.52923], [-94.71261, 29.53061], [-94.71194, 29.5267], [-94.7105, 29.52691], [-94.71193, 29.53236]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (5, 'Justin', 'Decline', 'Sassy Lady, Inc.', 'Galveston Bay', 53.53, '{"type": "Polygon", "coordinates": [[[-94.88542, 29.51506], [-94.88853, 29.5127], [-94.88554, 29.51133], [-94.88395, 29.50773], [-94.88118, 29.50929], [-94.88542, 29.51506]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (6, 'Justin', 'Accept', 'Sassy Lady, Inc.', 'Galveston Bay', 92.47, '{"type": "Polygon", "coordinates": [[[-94.84273, 29.49443], [-94.84961, 29.49143], [-94.84762, 29.48757], [-94.84069, 29.4897], [-94.84273, 29.49443]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (7, 'Justin', 'Modify', 'Sassy Lady, Inc.', 'Galveston Bay', 92.34, '{"type": "Polygon", "coordinates": [[[-94.70182, 29.47505], [-94.70699, 29.47286], [-94.70455, 29.47106], [-94.70275, 29.46837], [-94.70025, 29.47058], [-94.69782, 29.46775], [-94.69783, 29.47257], [-94.70182, 29.47505]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (8, 'Justin', 'Accept', 'Sassy Lady, Inc.', 'Galveston Bay', 52.27, '{"type": "Polygon", "coordinates": [[[-94.71843, 29.5297], [-94.72115, 29.52856], [-94.71683, 29.52013], [-94.71302, 29.52215], [-94.71315, 29.5241], [-94.7169, 29.52233], [-94.71938, 29.52741], [-94.71769, 29.52821], [-94.71843, 29.5297]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (9, 'Justin', 'Accept', 'Drum Village Reef, Inc.', 'Galveston Bay', 62.78, '{"type": "Polygon", "coordinates": [[[-94.79242, 29.4964], [-94.79607, 29.49407], [-94.79115, 29.4906], [-94.78831, 29.49582], [-94.79242, 29.4964]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (10, 'Justin', 'Decline', 'Big Ben, Inc.', 'San Antonio Bay', 62.69, '{"type": "Polygon", "coordinates": [[[-96.7249, 28.32997], [-96.72732, 28.32741], [-96.72184, 28.32163], [-96.72106, 28.32226], [-96.72154, 28.3259], [-96.7249, 28.32997]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (11, 'Justin', 'Decline', 'Big Ben, Inc.', 'San Antonio Bay', 60.19, '{"type": "Polygon", "coordinates": [[[-96.71772, 28.26781], [-96.72078, 28.26776], [-96.71986, 28.25922], [-96.71693, 28.26228], [-96.71772, 28.26781]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (12, 'Justin', 'Accept', 'Justin Woody', 'Galveston Bay', 39.3, '{"type": "Polygon", "coordinates": [[[-94.86479, 29.50842], [-94.86559, 29.50597], [-94.86141, 29.50364], [-94.86035, 29.50732], [-94.86479, 29.50842]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (13, 'Justin', 'Modify', 'Justin Woody', 'Galveston Bay', 74.49, '{"type": "Polygon", "coordinates": [[[-94.8345, 29.49132], [-94.84093, 29.48933], [-94.83903, 29.48488], [-94.83694, 29.48525], [-94.83682, 29.48671], [-94.8332, 29.48755], [-94.8345, 29.49132]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (14, 'Justin', 'Accept', 'Justin Woody', 'Galveston Bay', 33.05, '{"type": "Polygon", "coordinates": [[[-94.80522, 29.54912], [-94.80897, 29.54754], [-94.80805, 29.54491], [-94.80328, 29.54721], [-94.80522, 29.54912]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (15, 'Justin', 'Accept', 'Justin Woody', 'Galveston Bay', 49.01, '{"type": "Polygon", "coordinates": [[[-94.81266, 29.51773], [-94.81484, 29.51682], [-94.81452, 29.51436], [-94.81656, 29.51343], [-94.81595, 29.51234], [-94.80859, 29.51542], [-94.81266, 29.51773]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (16, 'Justin', 'Modify', 'Justin Woody', 'Galveston Bay', 93.76, '{"type": "Polygon", "coordinates": [[[-94.71944, 29.48726], [-94.73056, 29.4797], [-94.72813, 29.47804], [-94.71796, 29.48493], [-94.71944, 29.48726]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (17, 'Justin', 'Accept', 'Sheldon Reef, Inc.', 'Galveston Bay', 71.19, '{"type": "Polygon", "coordinates": [[[-94.69617, 29.53479], [-94.69847, 29.53447], [-94.69612, 29.52684], [-94.69335, 29.52581], [-94.69534, 29.52804], [-94.69168, 29.52825], [-94.69617, 29.53479]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (18, 'Justin', 'Decline', 'Miss Terri, Inc.', 'Aransas Bay', 81.94, '{"type": "Polygon", "coordinates": [[[-96.93451, 28.09284], [-96.93937, 28.08768], [-96.93569, 28.08531], [-96.93084, 28.0905], [-96.93451, 28.09284]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (19, 'Justin', 'Accept', 'Miss Terri, Inc.', 'San Antonio Bay', 98.98, '{"type": "Polygon", "coordinates": [[[-96.77959, 28.3364], [-96.77966, 28.33276], [-96.76894, 28.33258], [-96.76867, 28.33385], [-96.77108, 28.33626], [-96.77959, 28.3364]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (20, 'Justin', 'Decline', 'Miss Terri, Inc.', 'San Antonio Bay', 98.68, '{"type": "Polygon", "coordinates": [[[-96.70855, 28.25087], [-96.71572, 28.24922], [-96.71404, 28.24451], [-96.7068, 28.24617], [-96.70855, 28.25087]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (21, 'Justin', 'Decline', 'Miss Britney, Inc.', 'Aransas Bay', 62.9, '{"type": "Polygon", "coordinates": [[[-96.97742, 28.0774], [-96.97802, 28.07604], [-96.98136, 28.07648], [-96.98201, 28.07314], [-96.9772, 28.07232], [-96.97519, 28.07448], [-96.97583, 28.07717], [-96.97742, 28.0774]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (22, 'Justin', 'Accept', 'Miss Britney, Inc.', 'Galveston Bay', 32.59, '{"type": "Polygon", "coordinates": [[[-94.74768, 29.4886], [-94.74983, 29.48833], [-94.7488, 29.48273], [-94.74666, 29.48299], [-94.74768, 29.4886]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (23, 'Justin', 'Accept', 'Miss Britney, Inc.', 'San Antonio Bay', 70.97, '{"type": "Polygon", "coordinates": [[[-96.77985, 28.3238], [-96.77993, 28.31975], [-96.77216, 28.31961], [-96.77213, 28.32111], [-96.77412, 28.32114], [-96.77405, 28.3237], [-96.77985, 28.3238]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (24, 'Justin', 'Accept', 'Miss Britney, Inc.', 'San Antonio Bay', 99.05, '{"type": "Polygon", "coordinates": [[[-96.66173, 28.25938], [-96.6637, 28.25491], [-96.65736, 28.25272], [-96.65349, 28.25623], [-96.66173, 28.25938]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (25, 'Justin', 'Accept', 'Nightmare, Inc.', 'Galveston Bay', 25.63, '{"type": "Polygon", "coordinates": [[[-94.86871, 29.44648], [-94.87214, 29.4438], [-94.86837, 29.44216], [-94.86785, 29.44613], [-94.86871, 29.44648]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (26, 'Justin', 'Modify', 'Nightmare, Inc.', 'Galveston Bay', 91.22, '{"type": "Polygon", "coordinates": [[[-94.72691, 29.49113], [-94.73234, 29.48811], [-94.73117, 29.48603], [-94.73042, 29.48665], [-94.73034, 29.48427], [-94.72153, 29.49025], [-94.72209, 29.49106], [-94.72691, 29.49113]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (27, 'Justin', 'Modify', 'Nightmare, Inc.', 'Galveston Bay', 84.0, '{"type": "Polygon", "coordinates": [[[-94.72222, 29.48143], [-94.71611, 29.47565], [-94.71148, 29.4788], [-94.71722, 29.48143], [-94.72222, 29.48143]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (28, 'Justin', 'Accept', 'Nightmare, Inc.', 'Galveston Bay', 72.82, '{"type": "Polygon", "coordinates": [[[-94.69707, 29.46687], [-94.70224, 29.46229], [-94.69872, 29.45765], [-94.69701, 29.45827], [-94.69707, 29.46687]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (29, 'Justin', 'Decline', 'Mr. Clint Incorporated', 'Aransas Bay', 85.29, '{"type": "Polygon", "coordinates": [[[-96.95809, 28.07638], [-96.95964, 28.07376], [-96.9506, 28.06939], [-96.94876, 28.07208], [-96.95809, 28.07638]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (30, 'Justin', 'Decline', 'Mr. Clint Incorporated', 'Matagorda Bay', 61.77, '{"type": "Polygon", "coordinates": [[[-96.51719, 28.60677], [-96.5229, 28.60486], [-96.52123, 28.60104], [-96.5168, 28.6021], [-96.51719, 28.60677]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (31, 'Justin', 'Decline', 'Mr. Clint Incorporated', 'San Antonio Bay', 18.76, '{"type": "Polygon", "coordinates": [[[-96.7269, 28.29468], [-96.72848, 28.29438], [-96.72701, 28.29023], [-96.72544, 28.29053], [-96.7269, 28.29468]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (32, 'Justin', 'Decline', 'Mr. Clint Incorporated', 'San Antonio Bay', 98.66, '{"type": "Polygon", "coordinates": [[[-96.70671, 28.24591], [-96.71394, 28.24424], [-96.71227, 28.23957], [-96.70499, 28.24125], [-96.70671, 28.24591]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (33, 'Johny', 'Decline', 'Moses Lake Properties, LLC', 'Aransas Bay', 84.2, '{"type": "Polygon", "coordinates": [[[-96.94786, 28.06751], [-96.95486, 28.07112], [-96.95848, 28.0671], [-96.95569, 28.06521], [-96.94786, 28.06751]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (34, 'Johny', 'Modify', 'Moses Lake Properties, LLC', 'Galveston Bay', 19.42, '{"type": "Polygon", "coordinates": [[[-94.87429, 29.44182], [-94.87449, 29.44191], [-94.87918, 29.43821], [-94.87695, 29.43711], [-94.87429, 29.44182]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (37, 'Johny', 'Decline', 'John Jurisich', 'San Antonio Bay', 98.52, '{"type": "Polygon", "coordinates": [[[-96.71529, 28.25499], [-96.71706, 28.25298], [-96.71581, 28.24948], [-96.70864, 28.25113], [-96.71048, 28.2561], [-96.71529, 28.25499]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (50, 'Johny', 'Accept', 'Calhoun County Channel & Dock, Inc.', 'San Antonio Bay', 77.46, '{"type": "Polygon", "coordinates": [[[-96.72012, 28.31973], [-96.72316, 28.32091], [-96.72495, 28.31746], [-96.72555, 28.31411], [-96.72146, 28.31277], [-96.72012, 28.31973]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (51, 'Johny', 'Decline', 'Calhoun County Channel & Dock, Inc.', 'San Antonio Bay', 60.66, '{"type": "Polygon", "coordinates": [[[-96.7316, 28.30676], [-96.72962, 28.29874], [-96.72663, 28.29932], [-96.72856, 28.30623], [-96.7316, 28.30676]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (52, 'Johny', 'Decline', 'Calhoun County Channel & Dock, Inc.', 'San Antonio Bay', 63.17, '{"type": "Polygon", "coordinates": [[[-96.72239, 28.27795], [-96.72005, 28.2716], [-96.72102, 28.27], [-96.72081, 28.26803], [-96.71776, 28.26809], [-96.71866, 28.27435], [-96.72046, 28.2781], [-96.72239, 28.27795]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (53, 'Johny', 'Accept', 'Calhoun County Channel & Dock, Inc.', 'San Antonio Bay', 18.0, '{"type": "Polygon", "coordinates": [[[-96.71161, 28.25916], [-96.71498, 28.25535], [-96.71057, 28.25636], [-96.71161, 28.25916]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (54, 'Johny', 'Decline', 'Calhoun County Channel & Dock, Inc.', 'San Antonio Bay', 76.23, '{"type": "Polygon", "coordinates": [[[-96.70923, 28.22518], [-96.70772, 28.22117], [-96.70094, 28.22221], [-96.70123, 28.22567], [-96.70923, 28.22518]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (55, 'Johny', 'Modify', 'Ruzica Jurisich', 'Galveston Bay', 91.99, '{"type": "Polygon", "coordinates": [[[-94.8404, 29.48979], [-94.83459, 29.49158], [-94.83651, 29.49713], [-94.84244, 29.49455], [-94.8404, 29.48979]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (56, 'Johny', 'Accept', 'Ruzica Jurisich', 'Galveston Bay', 82.0, '{"type": "Polygon", "coordinates": [[[-94.74178, 29.47562], [-94.73894, 29.4763], [-94.73709, 29.47917], [-94.73602, 29.47955], [-94.73761, 29.48242], [-94.74352, 29.48095], [-94.74178, 29.47562]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (57, 'Johny', 'Accept', 'Ruzica Jurisich', 'Galveston Bay', 78.16, '{"type": "Polygon", "coordinates": [[[-94.70705, 29.46496], [-94.70314, 29.46841], [-94.70355, 29.46903], [-94.70492, 29.46933], [-94.7061, 29.46875], [-94.70992, 29.4724], [-94.7127, 29.47039], [-94.70705, 29.46496]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (72, 'Johny', 'Modify', 'Moses Lake Harbor, Inc.', 'Galveston Bay', 98.56, '{"type": "Polygon", "coordinates": [[[-94.87959, 29.42601], [-94.87734, 29.42906], [-94.88612, 29.43273], [-94.88939, 29.4301], [-94.87959, 29.42601]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (73, 'Johny', 'Accept', 'Moses Lake Harbor, Inc.', 'Galveston Bay', 22.6, '{"type": "Polygon", "coordinates": [[[-94.80781, 29.52055], [-94.80719, 29.52084], [-94.80999, 29.5259], [-94.81101, 29.52297], [-94.8091, 29.52114], [-94.80781, 29.52055]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (74, 'Johny', 'Modify', 'Moses Lake Harbor, Inc.', 'Galveston Bay', 71.64, '{"type": "Polygon", "coordinates": [[[-94.80877, 29.5019], [-94.80738, 29.5055], [-94.80809, 29.50949], [-94.81436, 29.50677], [-94.80877, 29.5019]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (75, 'Johny', 'Accept', 'Moses Lake Harbor, Inc.', 'Galveston Bay', 80.74, '{"type": "Polygon", "coordinates": [[[-94.75314, 29.47562], [-94.75185, 29.47626], [-94.75799, 29.48254], [-94.76177, 29.48171], [-94.76168, 29.47951], [-94.7576, 29.47716], [-94.75585, 29.47745], [-94.75314, 29.47562]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (87, 'Johny', 'Decline', 'Mermaid Seafood, Inc.', 'Matagorda Bay', 83.4, '{"type": "Polygon", "coordinates": [[[-96.49734, 28.61127], [-96.48758, 28.6038], [-96.48526, 28.6062], [-96.4931, 28.61127], [-96.49734, 28.61127]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (88, 'Johny', 'Decline', 'Mermaid Seafood, Inc.', 'San Antonio Bay', 98.63, '{"type": "Polygon", "coordinates": [[[-96.71042, 28.23441], [-96.70878, 28.22981], [-96.70138, 28.23151], [-96.70308, 28.2361], [-96.71042, 28.23441]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (89, 'Johny', 'Decline', 'Mermaid Seafood, Inc.', 'San Antonio Bay', 99.0, '{"type": "Polygon", "coordinates": [[[-96.69937, 28.22606], [-96.70129, 28.23125], [-96.70868, 28.22955], [-96.70727, 28.22558], [-96.69937, 28.22606]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (90, 'Johny', 'Decline', 'Jurisich Holdings, LLC', 'Aransas Bay', 63.0, '{"type": "Polygon", "coordinates": [[[-96.98231, 28.07319], [-96.98166, 28.07652], [-96.98459, 28.07691], [-96.98781, 28.0794], [-96.99034, 28.07975], [-96.99055, 28.07815], [-96.98656, 28.07611], [-96.9848, 28.07361], [-96.98231, 28.07319]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (91, 'Johny', 'Decline', 'Jurisich Holdings, LLC', 'Aransas Bay', 76.71, '{"type": "Polygon", "coordinates": [[[-96.97287, 28.08353], [-96.97561, 28.0823], [-96.97583, 28.08001], [-96.97508, 28.07861], [-96.96876, 28.08001], [-96.97287, 28.08353]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (92, 'Johny', 'Decline', 'Jurisich Holdings, LLC', 'Aransas Bay', 76.79, '{"type": "Polygon", "coordinates": [[[-96.94144, 28.06812], [-96.94848, 28.07195], [-96.95033, 28.06926], [-96.94243, 28.06475], [-96.94144, 28.06812]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (93, 'Johny', 'Accept', 'Jurisich Holdings, LLC', 'San Antonio Bay', 80.54, '{"type": "Polygon", "coordinates": [[[-96.66547, 28.25523], [-96.66781, 28.25201], [-96.66081, 28.24959], [-96.6576, 28.25251], [-96.66547, 28.25523]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (94, 'Johny', 'Modify', 'Jurisich & Sons, Inc.', 'Galveston Bay', 73.43, '{"type": "Polygon", "coordinates": [[[-94.70749, 29.47287], [-94.70416, 29.47511], [-94.71108, 29.47872], [-94.71533, 29.47585], [-94.7115, 29.47593], [-94.70901, 29.47288], [-94.70749, 29.47287]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (95, 'Johny', 'Decline', 'Jurisich & Sons, Inc.', 'Matagorda Bay', 62.23, '{"type": "Polygon", "coordinates": [[[-96.52302, 28.60512], [-96.51722, 28.60706], [-96.51756, 28.61101], [-96.52426, 28.60797], [-96.52302, 28.60512]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (96, 'Johny', 'Accept', 'Jurisich & Sons, Inc.', 'San Antonio Bay', 71.13, '{"type": "Polygon", "coordinates": [[[-96.77395, 28.32854], [-96.77975, 28.32864], [-96.77984, 28.32407], [-96.77405, 28.32398], [-96.77395, 28.32854]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (97, 'Johny', 'Decline', 'Frances Jurisich', 'Aransas Bay', 92.08, '{"type": "Polygon", "coordinates": [[[-96.93891, 28.09565], [-96.94376, 28.0905], [-96.93962, 28.08784], [-96.93476, 28.093], [-96.93891, 28.09565]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (98, 'Johny', 'Accept', 'Frances Jurisich', 'Galveston Bay', 74.54, '{"type": "Polygon", "coordinates": [[[-94.84563, 29.4837], [-94.83934, 29.48482], [-94.84123, 29.48924], [-94.84749, 29.48731], [-94.84563, 29.4837]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (99, 'Johny', 'Accept', 'John Jurisich', 'Galveston Bay', 29.49, '{"type": "Polygon", "coordinates": [[[-94.88692, 29.43956], [-94.89195, 29.44163], [-94.8906, 29.43666], [-94.88692, 29.43956]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (100, 'Johny', 'Decline', 'John Jurisich', 'Galveston Bay', 60.55, '{"type": "Polygon", "coordinates": [[[-94.88101, 29.50906], [-94.88383, 29.50747], [-94.88301, 29.50518], [-94.88156, 29.5041], [-94.88262, 29.50227], [-94.88121, 29.50208], [-94.87898, 29.50313], [-94.87816, 29.5052], [-94.88101, 29.50906]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (101, 'Johny', 'Decline', 'John Jurisich', 'Galveston Bay', 45.11, '{"type": "Polygon", "coordinates": [[[-94.87337, 29.49718], [-94.87513, 29.49947], [-94.88027, 29.49641], [-94.87855, 29.49417], [-94.87337, 29.49718]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (102, 'Johny', 'Accept', 'John Jurisich', 'Galveston Bay', 39.05, '{"type": "Polygon", "coordinates": [[[-94.86028, 29.50758], [-94.85937, 29.51072], [-94.8637, 29.51179], [-94.86471, 29.50869], [-94.86028, 29.50758]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (103, 'Johny', 'Modify', 'Fisher Channel & Dock, Inc.', 'San Antonio Bay', 94.5, '{"type": "Polygon", "coordinates": [[[-96.76672, 28.3347], [-96.76711, 28.33631], [-96.76918, 28.34036], [-96.77974, 28.34058], [-96.77969, 28.33736], [-96.77239, 28.33885], [-96.76756, 28.33416], [-96.76672, 28.3347]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (104, 'Johny', 'Accept', 'Fisher Channel & Dock, Inc.', 'San Antonio Bay', 99.03, '{"type": "Polygon", "coordinates": [[[-96.77967, 28.33249], [-96.77974, 28.32891], [-96.76977, 28.32875], [-96.769, 28.33231], [-96.77967, 28.33249]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (105, 'Johny', 'Decline', 'Fisher Channel & Dock, Inc.', 'San Antonio Bay', 98.65, '{"type": "Polygon", "coordinates": [[[-96.71217, 28.23931], [-96.71052, 28.23467], [-96.70318, 28.23636], [-96.70489, 28.24099], [-96.71217, 28.23931]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (106, 'Johny', 'Accept', 'Adrian Oysters, Inc.', 'Galveston Bay', 93.54, '{"type": "Polygon", "coordinates": [[[-94.87634, 29.43429], [-94.87736, 29.4354], [-94.87703, 29.43684], [-94.87943, 29.43802], [-94.88587, 29.43293], [-94.88077, 29.4308], [-94.87634, 29.43429]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (107, 'Johny', 'Accept', 'Capt. Johny Jurisich, LP', 'Galveston Bay', 99.72, '{"type": "Polygon", "coordinates": [[[-94.75181, 29.47077], [-94.74656, 29.47243], [-94.74838, 29.47462], [-94.75465, 29.47458], [-94.75533, 29.47372], [-94.76134, 29.47391], [-94.76087, 29.47192], [-94.75739, 29.4711], [-94.75336, 29.472], [-94.75181, 29.47077]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (108, 'Johny', 'Accept', 'Capt. Johny Jurisich, LP', 'Galveston Bay', 93.69, '{"type": "Polygon", "coordinates": [[[-94.72989, 29.4805], [-94.7196, 29.48749], [-94.72136, 29.49002], [-94.73002, 29.48414], [-94.72989, 29.4805]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (109, 'Johny', 'Modify', 'Capt. Johny Jurisich, LP', 'Galveston Bay', 82.87, '{"type": "Polygon", "coordinates": [[[-94.71825, 29.48483], [-94.72787, 29.47787], [-94.72537, 29.47615], [-94.72377, 29.47617], [-94.72235, 29.47831], [-94.71735, 29.48169], [-94.71825, 29.48483]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (112, 'Johny', 'Accept', 'Frances Jurisich', 'Aransas Bay', 56.25, '{"type": "Polygon", "coordinates": [[[-97.03189, 28.14468], [-97.03791, 28.14716], [-97.03932, 28.14636], [-97.03577, 28.14105], [-97.03189, 28.14468]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (113, 'Johny', 'Accept', 'John Jurisich', 'Aransas Bay', 21.62, '{"type": "Polygon", "coordinates": [[[-97.01646, 28.09904], [-97.01847, 28.10032], [-97.02, 28.09666], [-97.01753, 28.09641], [-97.01646, 28.09904]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (115, 'Johny', 'Decline', 'Moses Lake Properties, LLC', 'Aransas Bay', 68.73, '{"type": "Polygon", "coordinates": [[[-97.0872, 28.14833], [-97.08791, 28.15009], [-97.09091, 28.15352], [-97.09364, 28.15145], [-97.09088, 28.14601], [-97.0872, 28.14833]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (116, 'Johny', 'Decline', 'Moses Lake Properties, LLC', 'Aransas Bay', 68.74, '{"type": "Polygon", "coordinates": [[[-97.08488, 28.14254], [-97.08709, 28.14806], [-97.09075, 28.14575], [-97.08767, 28.13967], [-97.08488, 28.14254]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (117, 'Johny', 'Decline', 'Sea Gun Holdings, LLC', 'Aransas Bay', 89.06, '{"type": "Polygon", "coordinates": [[[-97.06996, 28.13928], [-97.07427, 28.14635], [-97.07835, 28.14152], [-97.07702, 28.1392], [-97.06996, 28.13928]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (118, 'Johny', 'Decline', 'Sea Gun Holdings, LLC', 'Aransas Bay', 97.77, '{"type": "Polygon", "coordinates": [[[-97.01169, 28.10658], [-97.01067, 28.10999], [-97.01899, 28.11518], [-97.02125, 28.11251], [-97.01169, 28.10658]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (119, 'Johny', 'Decline', 'Sea Gun Holdings, LLC', 'Aransas Bay', 85.98, '{"type": "Polygon", "coordinates": [[[-96.99596, 28.11514], [-97.0027, 28.11832], [-97.00581, 28.1179], [-97.00617, 28.11546], [-96.99524, 28.11255], [-96.99596, 28.11514]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
insert into public.col_applications (id, group_name, status, applicant, bay_system, acreage, geometry) values (120, 'Johny', 'Modify', 'Captain J Seafood, Inc.', 'Galveston Bay', 97.67, '{"type": "Polygon", "coordinates": [[[-94.93202, 29.25777], [-94.93623, 29.25104], [-94.93154, 29.25105], [-94.92571, 29.25651], [-94.93202, 29.25777]]]}'::jsonb)
  on conflict (id) do update set
    group_name = excluded.group_name,
    applicant  = excluded.applicant,
    bay_system = excluded.bay_system,
    acreage    = excluded.acreage,
    geometry   = excluded.geometry;
