/**
 * Reference layers — permit areas, restoration reefs, and anything else that
 * is context rather than a COL application.
 *
 * Generated by scripts/import_layers.py into public/layers/, so adding one is
 * a matter of dropping a shapefile in the repo and re-running the script; no
 * code changes. They are fetched at runtime rather than bundled so a large
 * layer never lands in the JavaScript payload.
 */

export type LayerMeta = {
  id: string;
  label: string;
  file: string;
  geometryType: string;
  features: number;
  /** [west, south, east, north] */
  bounds: [number, number, number, number];
  acres: number | null;
  color: string;
};

export async function fetchLayerIndex(): Promise<LayerMeta[]> {
  try {
    const response = await fetch("/layers/index.json", { cache: "no-store" });
    if (!response.ok) return [];
    const data = await response.json();
    return Array.isArray(data) ? (data as LayerMeta[]) : [];
  } catch {
    // No layers is a normal state, not a failure worth surfacing.
    return [];
  }
}

export async function fetchLayerGeoJSON(layer: LayerMeta) {
  const response = await fetch(`/layers/${layer.file}`, { cache: "force-cache" });
  if (!response.ok) throw new Error(`Could not load ${layer.label}.`);
  return response.json();
}
